### ISSUE TITLE
No titles for configuration and what port?

### ISSUE THREAD

**Issue by rverstappen** [brianhealey/hacs_amplipi#16]
I just downloaded and added this to HACS and the integration config shows two unlabeled input fields: presumably an IP address and a port but what should the port number be assuming that's what it is?
<img width="457" alt="Screenshot 2023-04-08 at 13 58 39" src="https://user-images.githubusercontent.com/1036495/230736147-9a4dbee4-df56-47a2-8f1e-ff7cf6059ed9.png">

**Comment by rverstappen** [comment]
Retrying this, it autofilled with port 80 and worked.

**Comment by linknum23** [comment]
Sorry about that this is due to a bug in amplipi's MDNS advertisement. We have been prototyping a fix but it hasn't made it to production yet: https://github.com/micro-nova/AmpliPi/issues/432
