### ISSUE TITLE
Allow a Zone to change which Source it is associated with

### ISSUE THREAD

**Issue by brianhealey** [brianhealey/hacs_amplipi#4]
Zones and Groups are associated with 1 of the 4 sources of the AmpliPi parent controller. 

Currently the integration doesn't have the ability to modify which source a zone or group is associated with. It would be useful to be able to view the available sources and allow for the source to be changed.

Existing implementations are discussed here: https://amplipi.discourse.group/t/home-assistant-temporary-rest-integration/77/3

**Comment by brianhealey** [comment]
I pushed initial support for this and am looking for feedback. [@hawk](https://github.com/hawkeyeP), if you wouldn't mind testing it out, I would appreciate it.

**Comment by hawkeyeP** [comment]
It looks like it is working. Thanks!

My setup does not currently have any groups, but I think the comments below would apply to groups as well.

Input source options are 'None', 'local', and 'stream=1000'
1.  Is there a reason for the "stream=", it would be less to parse  and cleaner if the options were 'None', 'local' or STREAM_NUMBER (ie 1000).  Maybe I'm missing a usage case here.

Similar suggestion for Zones.
2. You have zones with source: 'Source 1',  'Source 2', 'Source 3', or 'Source 4'
It would be much simpler to parse and cleaner if the values were just 1, 2, 3 or 4.

Hope this is useful.  I'll let you know if I run into anything else.

**Comment by hawkeyeP** [comment]
I'm using the mini-media-player for the lovelace UI.  Something I noticed from my usage case and which may apply to other uses is that the list of sources shows up as 'stream=10001' or something like that in the dropdown.  But in the mini-media-player for Sonos the source list is a list of station names like you have, but the source itself is also the station name and not the id that is used behind the scenes.  So using "Groove Salad" as the source to index into the source list may be a better solution.

**Comment by brianhealey** [comment]
Would you mind testing with the latest release?  I refactored the source and source_list to include `None` and that might have cleared up what you are reporting.

**Comment by hawkeyeP** [comment]
Works!  And fixes https://github.com/brianhealey/pyamplipi/issues/5#issue-1251705079
