### ISSUE TITLE
Unable to add integration via hacs

### ISSUE THREAD

**Issue by drnichols** [brianhealey/hacs_amplipi#5]
I'm unable to add the integration via hacs as the AmpliPi integration is not found in the search for repository dialog.

I've installed manually and the integration is working well so far. Thanks for creating and sharing this.

**Comment by Jizzay1** [comment]
Smae issue here (Oct 12) not able to add integration via HACS. No integration is found by searching "amplipi"

**Comment by rwarner** [comment]
@drnichols @Jizzay1 fwiw I was able to get it to show up using `https://github.com/brianhealey/hacs_amplipi` as a custom repo. Then I think it said that it already exists or something and then let me add it.

Once adding it, it asked for two fields and I put in my AmpliPi IP address and the port 80 in the bottom field, pressed enter and it worked.

Relayed this issue to the team

**Comment by brianhealey** [comment]
This project is not registered with HACS, so this is expected.  You shouldn't have to manually add your amplipi as it should be discovered automatically if it's on the same network.

**Comment by Jizzay1** [comment]
> This project is not registered with HACS, so this is expected. You shouldn't have to manually add your amplipi as it should be discovered automatically if it's on the same network.

Hi Brian thanks for confirming.  I think we are all reacting to the info page that directs installation through HACS as a first step, which per your comment, appears to be incorrect and needs updating.  thanks!

Jay

![image](https://user-images.githubusercontent.com/87614052/205509432-b5e7aca1-b7ef-4aed-807e-638f7cceeab1.png)
