### ISSUE TITLE
Implement controls for internet radio

### ISSUE THREAD

**Issue by hawkeyeP** [brianhealey/hacs_amplipi#6]
This requires adding stop to [pyamplipi](https://github.com/brianhealey/pyamplipi)/pyamplipi/amplipi.py
I opened another ticket for that on that repo.

(https://github.com/brianhealey/hacs_amplipi/tree/main/custom_components/amplipi)/media_player.py
Line 251
Add 'internetradio'

```
            if self._current_stream is not None and self._current_stream.type in (
                    'internetradio',
                    'spotify',
                    'pandora'
            ):
                return SUPPORT_AMPLIPI_MEDIA
```

**Comment by linknum23** [comment]
Now that the source that's playing reports the controls  available (in
0.1.8) via info->supported_cmds this logic might now be needed.

**Comment by brianhealey** [comment]
@linknum23 @hawkeyeP thanks. I updated both the pyamplipi and hacs_amplipi to support the latest firmware, and dynamically determine visibility based upon the values from the amplipi api.
